PROJECT_NAME = qbittorrent(思可觅专版)
PROJECT_VERSION = 3.1.0alpha

os2 {
    DEFINES += VERSION=\'\"v$${PROJECT_VERSION}\"\'
} else {
    DEFINES += VERSION=\\\"v$${PROJECT_VERSION}\\\"
}

DEFINES += VERSION_MAJOR=3
DEFINES += VERSION_MINOR=1
DEFINES += VERSION_BUGFIX=0
